Repository tpcly/epsilon-lti, pull requests merged in 2023-12, with the labels that each got.

#136 Redesign start and end date selection #123
  Epsilon.Host.Frontend/src/components/SearchBox.vue
  Epsilon.Host.Frontend/src/components/TermDateFilter.vue
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfile.vue
Labels: General issue

#64 Adding the frontend competence document components to the performance dashboard
  Epsilon.Host.Frontend/src/api.generated.ts
  Epsilon.Host.Frontend/src/app.vue
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceDocument.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfile.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfileCell.vue
  Epsilon.Host.Frontend/src/components/competence/KpiMatrix.vue
  Epsilon.Host.Frontend/src/components/competence/KpiMatrixCell.vue
  Epsilon.Host.Frontend/src/components/competence/KpiTable.vue
  Epsilon.Host.Frontend/src/components/performance/CompetenceGraph.vue
  Epsilon.Host.Frontend/src/components/performance/PerformanceDashboard.vue
  Epsilon.Host.Frontend/src/pages/index.vue
  Epsilon.Host.Frontend/src/utils/posthog.ts
  Epsilon.Host.WebApi/Controllers/LearningController.cs
Labels: Competence generation

#121 Add a Unit Testing framework
  .github/workflows/continuous-integration.yml
  Epsilon.Abstractions/CompetenceDocument.cs
  Epsilon.Abstractions/LearningDomainTypeSet.cs
  Epsilon.UnitTest/Epsilon.UnitTest.csproj
  Epsilon.UnitTest/Services/AuthorizationUserTests.cs
  Epsilon.UnitTest/Services/CompetenceDocumentServiceTests.cs
  Epsilon.UnitTest/Services/LearningDomainServiceTests.cs
  Epsilon.UnitTest/TestDataGenerator.cs
  Epsilon.UnitTest/Usings.cs
  Epsilon.sln
  Epsilon/Services/CompetenceDocumentService.cs
Labels: enhancement, General issue

#183 Fix competence document structure
  Epsilon.Abstractions/Components/AbstractCompetenceComponent.cs
  Epsilon.Abstractions/Components/IWordCompetenceComponent.cs
  Epsilon.Abstractions/Components/PageComponent.cs
  Epsilon.Abstractions/Services/ICompetenceDocumentService.cs
  Epsilon.Host.Frontend/src/pages/index.vue
  Epsilon.Host.WebApi/Controllers/DocumentController.cs
  Epsilon.UnitTest/Services/CompetenceDocumentServiceTests.cs
  Epsilon/Components/CompetenceProfileComponent.cs
  Epsilon/Services/CompetenceDocumentService.cs
  Epsilon/Services/LearningOutcomeCanvasResultService.cs
Labels: bug, Competence generation

#184 Changing general UI issues
  Epsilon.Host.Frontend/.eslintrc
  Epsilon.Host.Frontend/nuxt.config.ts
  Epsilon.Host.Frontend/src/api.generated.ts
  Epsilon.Host.Frontend/src/assets/default_avatar.png
  Epsilon.Host.Frontend/src/assets/logo-white.png
  Epsilon.Host.Frontend/src/assets/vite.svg
  Epsilon.Host.Frontend/src/assets/vue.svg
  Epsilon.Host.Frontend/src/components/LearningDomainValues.vue
  Epsilon.Host.Frontend/src/components/SearchBox.vue
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceDocument.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfile.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfileCell.vue
  Epsilon.Host.Frontend/src/components/performance/CompetenceGraph.vue
  Epsilon.Host.Frontend/src/components/performance/PerformanceDashboard.vue
  Epsilon.Host.Frontend/src/components/performance/PersonalDevelopmentGraph.vue
  Epsilon.Host.Frontend/src/pages/index.vue
  Epsilon.Host.Frontend/src/utils/decaying-average.ts
  Epsilon.Host.Frontend/src/utils/generator.ts
  Epsilon/Services/FilterService.cs
Labels: General issue

#203 Fix for CI/CD steps
  .github/release.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/releaser.yml
  Epsilon.Host.Frontend/package.json
Labels: bug, General issue

#211 Added percentage to bar chart CompetenceGraph.vue
  Epsilon.Host.Frontend/src/components/performance/CompetenceGraph.vue
Labels: enhancement, Performance dashboard

#226 Add a responsive design for mobile friendly use.
  Epsilon.Host.Frontend/nuxt.config.ts
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfile.vue
  Epsilon.Host.Frontend/src/components/performance/CompetenceGraph.vue
  Epsilon.Host.Frontend/src/components/performance/PerformanceDashboard.vue
  Epsilon.Host.Frontend/src/pages/index.vue
Labels: enhancement, General issue
