Repository tpcly/epsilon-lti, pull requests merged in 2023-11, with the labels that each got.

#45 Change dashboard layout issues #32 #40
  Epsilon.Host.Frontend/src/components/Competence/CompetenceProfile.vue
  Epsilon.Host.Frontend/src/components/Competence/CompetenceProfileCell.vue
  Epsilon.Host.Frontend/src/components/Competence/KpiMatrix.vue
  Epsilon.Host.Frontend/src/components/Competence/KpiMatrixCell.vue
  Epsilon.Host.Frontend/src/components/Competence/KpiTable.vue
  Epsilon.Host.Frontend/src/components/CompetenceProfileLegend.vue
  Epsilon.Host.Frontend/src/components/Performance/CompetenceGraph.vue
  Epsilon.Host.Frontend/src/components/Performance/PersonalDevelopmentGraph.vue
  Epsilon.Host.Frontend/src/components/SearchBox.vue
  Epsilon.Host.Frontend/src/components/TermDateFilter.vue
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
Labels: Performance dashboard

#66 Added automation versioning tools
  .editorconfig
  .github/dependabot.yml
  Epsilon.Host.WebApi/Data/Migrations/20230623134631_AddLearningDomains.cs
Labels: General issue

#60 Add software for User testing
  Epsilon.Host.Frontend/package.json
  Epsilon.Host.Frontend/pnpm-lock.yaml
  Epsilon.Host.Frontend/src/app.vue
  Epsilon.Host.Frontend/src/main.ts
  Epsilon.Host.Frontend/src/utils/posthog.ts
Labels: Performance dashboard

#112 Bugfix: Check criteria on existing domain outcomes
  Epsilon/Services/LearningOutcomeCanvasResultService.cs
Labels: bug, Competence generation, Blocking

#113 Add access and authorization flows to have student and teacher validation
  Epsilon.Abstractions/CanvasUserSession.cs
  Epsilon.Abstractions/Services/IAuthorizationUser.cs
  Epsilon.Abstractions/Services/IFilterService.cs
  Epsilon.Host.Frontend/package.json
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfileCell.vue
  Epsilon.Host.WebApi/CanvasUserSessionAccessor.cs
  Epsilon.Host.WebApi/Controllers/FilterController.cs
  Epsilon.Host.WebApi/Controllers/LearningController.cs
  Epsilon.Host.WebApi/Epsilon.Host.WebApi.csproj
  Epsilon.Host.WebApi/Program.cs
  Epsilon/Services/AuthorizationUser.cs
  Epsilon/Services/FilterService.cs
Labels: enhancement, General issue

#28 Add Structure for Competence components generation
  Epsilon.Abstractions/CompetenceDocument.cs
  Epsilon.Abstractions/Components/AbstractCompetenceComponent.cs
  Epsilon.Abstractions/Components/IPageComponentManager.cs
  Epsilon.Abstractions/Components/IWordCompetenceComponent.cs
  Epsilon.Abstractions/Epsilon.Abstractions.csproj
  Epsilon.Abstractions/LearningDomain.cs
  Epsilon.Abstractions/LearningDomainTypeSet.cs
  Epsilon.Abstractions/Services/ICompetenceDocumentService.cs
  Epsilon.Abstractions/Services/ILearningDomainService.cs
  Epsilon.Host.WebApi/Controllers/DocumentController.cs
  Epsilon/Components/CompetenceProfileComponent.cs
  Epsilon/Services/CompetenceDocumentService.cs
  Epsilon/Services/LearningDomainService.cs
Labels: Competence generation
