Repository tpcly/epsilon-lti, pull requests merged in 2024-01, with the labels that each got.

#201 Add Competence Document KPI table
  Epsilon.Host.WebApi/Controllers/DocumentController.cs
  Epsilon/Components/KpiTableComponent.cs
  Epsilon/Services/CompetenceDocumentService.cs
Labels: Competence generation

#202 Add Competence Document KPI matrix
  Epsilon.Abstractions/Components/AbstractCompetenceComponent.cs
  Epsilon.UnitTest/Services/CompetenceDocumentServiceTests.cs
  Epsilon/Components/CompetenceProfileComponent.cs
  Epsilon/Components/KpiMatrixComponent.cs
  Epsilon/Components/KpiTableComponent.cs
  Epsilon/Services/CompetenceDocumentService.cs
Labels: Competence generation

#222 Bug: Solve issue so that master key can read all submissions of user.
  Epsilon.Abstractions/Epsilon.Abstractions.csproj
  Epsilon.Abstractions/Services/IFilterService.cs
  Epsilon.Host.WebApi/Controllers/FilterController.cs
  Epsilon.Host.WebApi/Epsilon.Host.WebApi.csproj
  Epsilon/Services/FilterService.cs
  Epsilon/Services/LearningOutcomeCanvasResultService.cs
Labels: bug

#271 Bug fix: issue 260 - fix new Kpi's Mastered in Epsilon Wrapped
  Epsilon.Host.Frontend/src/api.generated.ts
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
  Epsilon.Host.Frontend/src/components/wrapped/WrappedDialog.vue
  Epsilon/Services/FilterService.cs
Labels: bug, Performance dashboard

#284 Fixed missing data after docker restart
  docker-compose.development.yml
  docker-compose.production.yml
  docker-compose.staging.yml
Labels: bug, General issue

#241 Update to coding rulesets
  .editorconfig
  Epsilon.Abstractions/Components/AbstractCompetenceComponent.cs
  Epsilon.Abstractions/LearningDomain.cs
  Epsilon.Abstractions/LearningDomainType.cs
  Epsilon.Host.Frontend/.eslintrc
  Epsilon.Host.Frontend/src/components/LayoutCol.vue
  Epsilon.Host.Frontend/src/components/LearningDomainValues.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceDocument.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfile.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceProfileCell.vue
  Epsilon.Host.Frontend/src/components/competence/KpiMatrix.vue
  Epsilon.Host.Frontend/src/components/competence/KpiMatrixCell.vue
  Epsilon.Host.Frontend/src/components/competence/KpiTable.vue
  Epsilon.Host.Frontend/src/components/performance/CompetenceGraph.vue
  Epsilon.Host.Frontend/src/components/performance/PersonalDevelopmentGraph.vue
  Epsilon.Host.Frontend/src/components/wrapped/WrappedDialog.vue
  Epsilon.Host.WebApi/CanvasUserSessionAccessor.cs
  Epsilon.Host.WebApi/Controllers/FilterController.cs
  Epsilon.Host.WebApi/Controllers/LearningController.cs
  Epsilon.Host.WebApi/Options/CanvasOptions.cs
  Epsilon.UnitTest/Services/CompetenceDocumentServiceTests.cs
  Epsilon.UnitTest/TestDataGenerator.cs
  Epsilon/Components/CompetenceProfileComponent.cs
  Epsilon/Services/AuthorizationUser.cs
  Epsilon/Services/FilterService.cs
  Epsilon/Services/LearningDomainService.cs
  Epsilon/Services/LearningOutcomeCanvasResultService.cs
Labels: enhancement, .NET, javascript

#273 Optimizing frontend related issues for first release
  Epsilon.Host.Frontend/package.json
  Epsilon.Host.Frontend/pnpm-lock.yaml
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
  Epsilon.Host.Frontend/src/components/competence/CompetenceGenerationBanner.vue
  Epsilon.Host.Frontend/src/components/performance/CompetenceGraph.vue
  Epsilon.Host.Frontend/src/components/performance/PersonalDevelopmentGraph.vue
  Epsilon.Host.Frontend/src/components/wrapped/WrappedDialog.vue
  Epsilon.Host.Frontend/src/composables/use-store.ts
  Epsilon.Host.Frontend/src/pages/index.vue
  Epsilon.Host.Frontend/src/plugins/pinia.ts
Labels: Performance dashboard, General issue

#294 Bugfix #293 bug after resubmit of assignment already graded kpis are not shown
  Epsilon/Services/LearningOutcomeCanvasResultService.cs
Labels: bug, General issue

#295 Bugfix #288 loading animation stops too fast
  Epsilon.Host.Frontend/src/pages/index.vue
Labels: bug, Performance dashboard

#296 Add redesigned date selection
  Epsilon.Host.Frontend/src/components/TopNavigation.vue
Labels: enhancement

#243 Feat/competence document generation
  Epsilon.Abstractions/CompetenceDocument.cs
  Epsilon.Abstractions/Components/AbstractCompetenceComponent.cs
  Epsilon.Abstractions/Components/IWordCompetenceComponent.cs
  Epsilon.Abstractions/OutcomeGradeStatus.cs
  Epsilon.Abstractions/Services/ICompetenceDocumentService.cs
  Epsilon.Abstractions/Services/ILearningDomainService.cs
  Epsilon.Host.WebApi/Controllers/DocumentController.cs
  Epsilon.UnitTest/Services/CompetenceDocumentServiceTests.cs
  Epsilon.UnitTest/Services/LearningDomainServiceTests.cs
  Epsilon.UnitTest/TestDataGenerator.cs
  Epsilon/Components/CompetenceProfileComponent.cs
  Epsilon/Components/KpiMatrixComponent.cs
  Epsilon/Components/KpiTableComponent.cs
  Epsilon/Components/TitleComponent.cs
  Epsilon/Services/CompetenceDocumentService.cs
  Epsilon/Services/LearningDomainService.cs
  Epsilon/Services/LearningOutcomeCanvasResultService.cs
Labels: Competence generation
